from ecommerce.models.affiliate import Affiliate
from ecommerce.models.bet import Bet
from ecommerce.models.client import UserAPI
from ecommerce.models.lottery import Lottery
from ecommerce.models.lottery_draw import LotteryDraw
from ecommerce.models.modality import Modality
from ecommerce.models.placing import Placing
from ecommerce.models.pule import Pule
from ecommerce.models.wallet import Wallet
from ecommerce.models.client import Client
from ecommerce.models.verification import Verification
from ecommerce.models.placing_modality import PlacingModality
from ecommerce.models.money_moviment import MoneyMoviment
from ecommerce.models.transaction import Transaction
from ecommerce.models.administration import AdministrativeUser
from ecommerce.models.affiliate_quotation import AffiliateQuotation
from ecommerce.models.quotation import Quotation
from ecommerce.models.quotation_modality import QuotationModality
from ecommerce.models.messages import MessagesTemplate
from ecommerce.models.first_deposit import FirstDeposit
from ecommerce.models.config import Config
from ecommerce.models.affiliate_config import AffiliateConfig