# Generated by Django 5.0.1 on 2024-04-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AffiliateRegisterInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Código de registro",
                        max_length=100,
                        verbose_name="Código",
                    ),
                ),
                (
                    "max_registrations",
                    models.IntegerField(
                        default=1, verbose_name="Quantidade máxima de registros"
                    ),
                ),
                (
                    "registrations",
                    models.IntegerField(default=0, verbose_name="Registros"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
