# Generated by Django 5.0.1 on 2024-04-15 02:52

import django.core.validators
import django.db.models.deletion
import payment.utils
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ecommerce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentConfigTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_deposit_value", models.FloatField(default=1000)),
                ("min_deposit_value", models.FloatField(default=1)),
                ("withdraw_auto_approve", models.BooleanField(default=False)),
                ("max_auto_withdraw_value", models.FloatField(default=1000)),
                ("min_auto_withdraw_value", models.FloatField(default=1)),
                ("max_withdraw_value", models.FloatField(default=1000)),
                ("min_withdraw_value", models.FloatField(default=1)),
                ("max_withdraw_value_per_day", models.FloatField(default=1000)),
                ("max_withdraw_count_per_day", models.IntegerField(default=10)),
            ],
            options={
                "verbose_name": "Configuração de pagamento",
                "verbose_name_plural": "Configurações de pagamento",
            },
        ),
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("APPROVED", "Aprovado"),
                            ("CANCELED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PIX", "Pix"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("BOLETO", "Boleto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00"))
                        ],
                    ),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_id", models.CharField(blank=True, max_length=512, null=True)),
                ("integration_order_id", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.userapi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de deposito",
                "verbose_name_plural": "Pedidos de deposito",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WithDrawRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("APPROVED", "Aprovado"),
                            ("CANCELED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pix_key",
                    models.CharField(
                        max_length=255, validators=[payment.utils.validate_pix_key]
                    ),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, max_length=512, unique=True),
                ),
                (
                    "integration_request_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "money_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ecommerce.transaction",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_withdraw_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.userapi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de saque",
                "verbose_name_plural": "Solicitações de saque",
                "ordering": ["-created_at"],
            },
        ),
    ]
