# Generated by Django 5.0.1 on 2024-04-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="bet_value",
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name="bet",
            name="cashout",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name="bet",
            name="profit",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name="moneymoviment",
            name="balance_after",
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name="moneymoviment",
            name="balance_before",
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name="moneymoviment",
            name="value",
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name="pule",
            name="cashout",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name="pule",
            name="profit",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="balance_after",
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="balance_before",
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="value",
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="bonus",
            field=models.DecimalField(decimal_places=10, default=5000.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="commission",
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="money",
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
